apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  name: as-default-pipeline-1 
spec:
  params:
    - name: git-url
      value: 'https://github.com/jduimovich/a-simple-app'
    - name: output-image
      value: demo
  pipelineRef:
    name: as-default-pipeline
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: as-git-default
 