apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  name: as-default-pipeline-3 
spec:
  params:
    - name: git-url
      value: 'https://github.com/jduimovich/a-simple-app'
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/build-managed-by-gitops/a-simple-app
  pipelineRef:
    name: as-default-pipeline
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: as-default-workspace 
 